version: '3.8'

services:
  eventstore.db:
    image: eventstore/eventstore:5.0.8-xenial
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_EXT_IP=172.18.0.2
      - EVENTSTORE_INT_IP=172.18.0.2
      - EVENTSTORE_INT_TCP_PORT=1112
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INT_HTTP_PORT=2112
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_DEV=true
    ports:
      - "1112:1112"
      - "1113:1113"
      - "2112:2112"
      - "2113:2113"
    volumes:
      - type: bind
        source: ./files/configuration/
        target: /etc/eventstore/
      - type: bind
        source: ./files/data/
        target: /var/lib/eventstore/
      - type: bind
        source: ./files/app-logs/
        target: /var/log/eventstore/